---
title: "Cabbages"
author: "Judy Insunza"
date: "09/09/2025"
output:
  html_document:
    df_print: paged
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(MASS)
veggy <- cabbages
```

# Introduction

<!--In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?!-->
 The cabbages data from the MASS package is loaded into a dataframe called veggy. Complete this report by answering the following two questions  
 
### Is there a difference in average VitC between c39 and c52 cultivation methods?  

# Methods

<!--Decide on your methods:  use "variable analysis" or other appropriate descriptors.  Make sure to choose at least one graphical method and at least one numerical method.!-->

# Results

<!--Divide this section into two sub-sections:  One for your descriptive  results and one for your inferential results.!-->

## Descriptive Results

### Graphical Descriptive Results

<!--Graphical results here.  Make sure to show your code.  Provide appropriate labels for axes, giving units if possible, and provide a good title for the graph, too.  Use the graphical results to describe the patterns if any that exist in the data as focused toward the research question!-->

### Numerical Descriptive Results

<!--Numerical results go here. Use the numerical results to describe the patterns if any that exist in the data as focused toward the research question!-->


The Q3 for C39 has a value of 54.75 which is lower than the Q1 for C52which is 58. As a result Q3 is higher than a Q1 means that they are significantly different.

## Inferential Results
This is measuring the amount of VitC content that is dependent upon the cultivation. The C52 box is higher than the top of the C39 box. this means the C52 significantly different than C39.

<!--State hypothesis clearly.  Make sure your discussion of the inferential test covers all the aspects that the test output produces, such as test statistic, p-value etc.  Make a decision about the null hypothesis, explain the assumptions on which the selected test/procedure was based, and why the chosen procedure satisfys the assumptions and is appropriate to answer the research question!-->

The chances of getting a a result like this .00000003405. This mean that they are differnt and not the same.

# Discussion and Conclusion

<!--Discussion and conclusion here.  If you found a relationship be sure to consider whether the relationship occurs because one of the variavbles causes the other, or whether they perhasps are related for some other reason.  Watch the chapter 6 videos from the GeorgeTown videos collection.!-->
